name: Terraform CI using GitHub

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    env:
      TF_VERSION: "1.7.0"
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform -chdir=env/dev init

      - name: Terraform Format Check
        run: terraform -chdir=env/dev fmt -check

      - name: Terraform Validate
        run: terraform -chdir=env/dev validate

      - name: Terraform Plan
        run: terraform -chdir=env/dev plan -out=tfplan